# nginx proxy address - http://172.17.0.1:8088

x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  shiori:
    image: ghcr.io/go-shiori/shiori:latest
    container_name: shiori-app
    restart: unless-stopped
    logging: *default-logging
    networks:
      - shiori
    ports:
      - "8088:8088"
    environment:
      TZ: ${TZ:-America/New_York}
      PUID: ${SERVICE_USER:-1000}
      PGID: ${SERVICE_GROUP:-1000}
    volumes:
      - ./rootfs/config/shiori:/config
      - ./rootfs/data/shiori:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  shiori:
    external: false
