# nginx proxy address - http://172.17.0.1:8088

name: shiori
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  app:
    image: ghcr.io/go-shiori/shiori:latest
    pull_policy: always
    container_name: shiori-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    logging: *default-logging
    networks:
      - shiori
    ports:
      - "172.17.0.1:8088:8080"
    environment:
      TZ: ${TZ:-America/New_York}
      SHIORI_DIR: /data
      SHIORI_DBMS: sqlite3
    volumes:
      - ./volumes/data/shiori:/data
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  shiori:
    name: shiori
    external: false
